const carros=[{marca: "Toyota",
	modelo: "Etios",
	ano: 2009,
	cor: "preto",
	quantidade_portas: 4,
	automatico: false},
	{marca: "Nissan",
	modelo: "Gol",
	ano: 2010,
	cor: "azul",
	quantidade_portas: 4,
	automatico: false},
	{marca: "Toyota",
	modelo: "Civic",
	ano: 2029,
	cor: "prata",
	quantidade_portas: 4,
	automatico: true}]

	console.log (carros)